version: "3"
services:
  api:
    build: ./api
    environment:
      - PORT=4000
      - DATABASE_URI=mongodb://database:27017/prueba_cabify
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - database
    command: ["npm", "run", "dev"]
  database:
    image: "mongo:latest"
    ports:
      - "27018:27017"
