version: "3"
services:
  api:
    build: ./api
    environment:
      - PORT=4000
      - DATABASE_URI=mongodb://database:27017/prueba_cabify
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - database
    command: ["npm", "run", "dev"]
  web:
    build: ./web
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
      - /web/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - API_URL=http://localhost:4000/api
    depends_on:
      - api
  e2e:
    build: ./e2e
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    depends_on:
      - api
      - web
  database:
    image: "mongo:latest"
    ports:
      - "27018:27017"
